ALTER TYPE "SocialPlatform" ADD VALUE IF NOT EXISTS 'WHATSAPP';
ALTER TYPE "SocialInboxMessageStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "SocialInboxMessageStatus" ADD VALUE IF NOT EXISTS 'READ';
